name: "whisper-large-v3"
backend: "python"
input [
    {
        name: "audio"
        data_type: TYPE_FP32
        dims: [-1]
    },
    {
        name: "sampling_rate"
        data_type: TYPE_INT32
        dims: [1]
    }
]
output [
    {
        name: "transcribed_text"
        data_type: TYPE_STRING
        dims: [-1]
    }
]

dynamic_batching {
    max_queue_delay_microseconds: 100
}

instance_group [
    {
        count: 1
        kind: KIND_GPU
        gpus: [0]
    }
]